server:
  extraArgs:
    - --insecure  # Disable SSL redirection as Ingress handles HTTPS

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - argocd.eks.devopsproject.org
    tls:
      - secretName: argocd-ingress-tls
        hosts:
          - argocd.eks.devopsproject.org
         