name: app-ci

on:
  push:
    branches: [ main, feat* ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO: ${{ vars.ECR_REPO_NAME }}
  ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ vars.ECR_REPO_NAME }}:$IMAGE_TAG
          docker build -t $IMAGE ./outline-apps
          docker push $IMAGE
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update deployment manifest image
        run: |
          sed -i "s|image: .*|image: $IMAGE|" k8s-manifest/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s-manifest/deployment.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update image $IMAGE_TAG"
            git push
          fi

      - name: Install kubectl
        run: |
          KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable-1.27.txt)
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name eks-prod-cluster --region us-east-1

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: Verify Argo CD CLI
        run: argocd version --client

      - name: Sync Argo CD apps
        run: |
          # Login to Argo CD server
          argocd login argocd.eks.devopsproject.org --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

          # Sync root app (App-of-Apps)
          argocd app sync root-app
  
