name: build
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["terraform"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  actions: read

defaults:
  run:
    working-directory: outline

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPO_NAME: outline_repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO_NAME: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG -f outline/Dockerfile app
          docker push $ECR_REGISTRY/${ECR_REPO_NAME}:$IMAGE_TAG
          echo "image_url=$ECR_REGISTRY/${ECR_REPO_NAME}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Scan image
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}"
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: 0
